#!/bin/sh

PARENT=`dirname $0`
PYTHON=`which $PARENT/python`
if test -z "$PYTHON" ; then
PYTHON=`which python2.7`
fi
if test -z "$PYTHON" ; then
PYTHON=`which python2.6`
fi
if test -z "$PYTHON" ; then
PYTHON=`which python2.5`
fi
if test -z "$PYTHON" ; then
PYTHON=`which python`
fi

$PYTHON $PARENT/rfZenHanCmd.py $*
exit $?
